- name: Setup Splunk Standalone Server
  hosts: splunk
  become: yes
  vars_files:
    - group_vars/all.yml
  vars:
    app_zip_url: "https://www.dropbox.com/scl/fi/yi82jkdxtjccss4kawa8p/Bots_V3_Splunkbase_apps-main.tar?rlkey=xnp2mxfdq2b0t7a3d83kcp63a&st=sy0hhyvm&dl=1"

  roles:
    - deploy_splunk_app

  tasks:
    - name: Ensure Splunk User Exists
      user:
        name: splunk
        shell: /bin/bash
        createhome: yes

    - name: Download and Add Tutorial Data to Splunk Monitoring
      become: yes
      become_user: splunk
      shell: |
        cd /tmp
        curl -o tutorialdata.zip https://docs.splunk.com/images/Tutorial/tutorialdata.zip
        /opt/splunk/bin/splunk add monitor /tmp/tutorialdata.zip -host_segment 3 -disabled 0 -auth admin:{{ splunk_instance.splunk_admin_password }}
      args:
        executable: /bin/bash

    - name: Download and Install Splunk BOTS v3 Dataset
      become: yes
      become_user: splunk
      shell: |
        cd /tmp
        curl -O https://botsdataset.s3.amazonaws.com/botsv3/botsv3_data_set.tgz
        /opt/splunk/bin/splunk install app "/tmp/botsv3_data_set.tgz" -auth admin:{{ splunk_instance.splunk_admin_password }}
      args:
        executable: /bin/bash

    - name: Ensure Splunk is running before restart
      become: yes
      become_user: splunk
      shell: "/opt/splunk/bin/splunk status || /opt/splunk/bin/splunk start"
      args:
        executable: /bin/bash

    - name: Restart Splunk
      become: yes
      become_user: root
      shell: "/opt/splunk/bin/splunk restart"
      args:
        executable: /bin/bash
